//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace otr_project_internal.Models
{
    public partial class Category
    {
        public Category()
        {
            this.ItemModels = new HashSet<ItemModel>();
            this.OrderDetailModels = new HashSet<OrderDetailModel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Agreement_Id { get; set; }
    
        public virtual Agreement Agreement { get; set; }
        public virtual ICollection<ItemModel> ItemModels { get; set; }
        public virtual ICollection<OrderDetailModel> OrderDetailModels { get; set; }
    }
    
}
