//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace otr_project_internal.Models
{
    public partial class Country
    {
        public Country()
        {
            this.Regions = new HashSet<Region>();
            this.ItemModels = new HashSet<ItemModel>();
            this.UserModels = new HashSet<UserModel>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Region> Regions { get; set; }
        public virtual ICollection<ItemModel> ItemModels { get; set; }
        public virtual ICollection<UserModel> UserModels { get; set; }
    }
    
}
