//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace otr_project_internal.Models
{
    public partial class OrderDetailModel
    {
        public int OrderDetailId { get; set; }
        public string OrderId { get; set; }
        public string ItemModelId { get; set; }
        public string ItemName { get; set; }
        public string ItemDesc { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime DrofoffDate { get; set; }
        public int NumberOfDays { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal SecurityDeposit { get; set; }
        public string OwnerCode { get; set; }
        public string RenterCode { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ItemModel ItemModel { get; set; }
        public virtual Order Order { get; set; }
    }
    
}
