//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace otr_project_internal.Models
{
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Agreement> Agreements { get; set; }
        public DbSet<Badge> Badges { get; set; }
        public DbSet<BlackoutDate> BlackoutDates { get; set; }
        public DbSet<CartItemModel> CartItemModels { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<EdmMetadata> EdmMetadatas { get; set; }
        public DbSet<FacebookUser> FacebookUsers { get; set; }
        public DbSet<ItemImageFileModel> ItemImageFileModels { get; set; }
        public DbSet<ItemModel> ItemModels { get; set; }
        public DbSet<MessageModel> MessageModels { get; set; }
        public DbSet<OrderDetailModel> OrderDetailModels { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<ThreadModel> ThreadModels { get; set; }
        public DbSet<UserImageFileModel> UserImageFileModels { get; set; }
        public DbSet<UserModel> UserModels { get; set; }
    }
}
