//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace otr_project_internal.Models
{
    public partial class ThreadModel
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string MessageModelId { get; set; }
        public System.DateTime Date { get; set; }
        public string Author_Email { get; set; }
    
        public virtual MessageModel MessageModel { get; set; }
        public virtual UserModel UserModel { get; set; }
    }
    
}
